-- MySQL Script generated by MySQL Workbench
-- Fri Apr 15 21:25:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tab_vaccinations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tab_vaccinations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tab_vaccinations` DEFAULT CHARACTER SET UTF8MB4_BIN ;
USE `tab_vaccinations` ;

-- -----------------------------------------------------
-- Table `tab_vaccinations`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_vaccinations`.`patients` (
  `pesel` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `local_no` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`pesel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_vaccinations`.`vaccinations_warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_vaccinations`.`vaccinations_warehouse` (
  `serial_no` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `producer` VARCHAR(45) NULL,
  `expiration_date` DATE NULL,
  PRIMARY KEY (`serial_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_vaccinations`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_vaccinations`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `admin` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_vaccinations`.`timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tab_vaccinations`.`timetable` (
  `id` INT NOT NULL,
  `inset_time` DATETIME NULL,
  `users_id` INT NOT NULL,
  `patients_pesel` INT NULL,
  `vaccinations_warehouse_serial_no` INT NULL,
  `payment` INT NULL,
  `activation_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_timetable_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_timetable_patients1_idx` (`patients_pesel` ASC) VISIBLE,
  INDEX `fk_timetable_vaccinations_warehouse1_idx` (`vaccinations_warehouse_serial_no` ASC) VISIBLE,
  CONSTRAINT `fk_timetable_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `tab_vaccinations`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timetable_patients1`
    FOREIGN KEY (`patients_pesel`)
    REFERENCES `tab_vaccinations`.`patients` (`pesel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timetable_vaccinations_warehouse1`
    FOREIGN KEY (`vaccinations_warehouse_serial_no`)
    REFERENCES `tab_vaccinations`.`vaccinations_warehouse` (`serial_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
